export type ActiveView =
  | "dashboard"
  | "products"
  | "brands"
  | "suppliers"
  | "recipes"
  | "inventory"
  | "shoppingList"
  | "purchases"
  | "production"
  | "sales"
  | "users"
  | "stores"
  | "profile"
  | "settings"
  | "termsOfUse";
